## Load & Inspect Data

In [1]:
%pip install seaborn

In [2]:
import pandas as pd
pd.plotting.register_matplotlib_converters()
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
print("Setup Complete")

Setup Complete

In [8]:
raw_data = pd.read_csv("sales_data.csv", index_col = "transaction_id")
raw_data.head()

,date,customer_id,gender,age,product_category,quantity,price_per_unit,total_amount
transaction_id,,,,,,,,
1,24/11/2023,CUST001,Male,34,Beauty,3,50,150
2,27/02/2023,CUST002,Female,26,Clothing,2,500,1000
3,13/01/2023,CUST003,Male,50,Electronics,1,30,30
4,21/05/2023,CUST004,Male,37,Clothing,1,500,500
5,06/05/2023,CUST005,Male,30,Beauty,2,50,100

## Cleaning and Type Fixes

In [12]:
raw_data.dtypes

date                  str
customer_id           str
gender                str
age                 int64
product_category      str
quantity            int64
price_per_unit      int64
total_amount        int64
dtype: object

In [ ]:
# need to fix date column's type and price_per_unit column's type

In [26]:
raw_data["date"] = pd.to_datetime(raw_data["date"], dayfirst = True)
raw_data["price_per_unit"] = raw_data.price_per_unit.astype("float64")
pd.set_option("display.float_format", lambda x: f"{x:.2f}")

In [ ]:
# view edits to data

In [22]:
raw_data.dtypes

date                datetime64[us]
customer_id                    str
gender                         str
age                          int64
product_category               str
quantity                     int64
price_per_unit             float64
total_amount                 int64
dtype: object

In [27]:
raw_data.head()

,date,customer_id,gender,age,product_category,quantity,price_per_unit,total_amount
transaction_id,,,,,,,,
1,2023-11-24,CUST001,Male,34,Beauty,3,50.00,150
2,2023-02-27,CUST002,Female,26,Clothing,2,500.00,1000
3,2023-01-13,CUST003,Male,50,Electronics,1,30.00,30
4,2023-05-21,CUST004,Male,37,Clothing,1,500.00,500
5,2023-05-06,CUST005,Male,30,Beauty,2,50.00,100

In [34]:
raw_data.isnull().sum()

date                0
customer_id         0
gender              0
age                 0
product_category    0
quantity            0
price_per_unit      0
total_amount        0
dtype: int64

In [ ]:
# this means that there is no missing values in the table

##